# rts.py

RTS_CODE = [
            "",
            "# --- Runtime Support (RTS) ---",
            "Lprints:",
            "\tlw $t0, 0($a0)        # load string length",
            "\taddu $t1, $a0, 4      # pointer to first char",
            "Lprints_loop:",
            "\tbeqz $t0, Lprints_done",
            "\tlb $a0, 0($t1)        # load byte into $a0",
            "\tli $v0, 11            # syscall 11: print char",
            "\tsyscall",
            "\taddu $t1, $t1, 1      # advance pointer",
            "\tsubu $t0, $t0, 1      # decrement length",
            "\tj Lprints_loop",
            "Lprints_done:",
            "\tjr $ra",
            "",
            "Lprinti:",
            "\tli $v0, 1             # syscall 1: print int",
            "\tsyscall",
            "\tjr $ra",
            "",
            "Lprintb:",
            "\tbnez $a0, Lprintb_true",
            "\t.data",
            "L_false_str: .asciiz \"false\"",
            "\t.text",
            "\tla $a0, L_false_str",
            "\tli $v0, 4             # syscall 4: print string",
            "\tsyscall",
            "\tjr $ra",
            "Lprintb_true:",
            "\t.data",
            "L_true_str: .asciiz \"true\"",
            "\t.text",
            "\tla $a0, L_true_str",
            "\tli $v0, 4             # syscall 4: print string",
            "\tsyscall",
            "\tjr $ra",
            "",
            "Lprintc:",
            "\tli $v0, 11            # syscall 11: print char",
            "\tsyscall",
            "\tjr $ra",
            "",
            "Lgetchar:",
            "\t.data",
            "\tLgetchar_buf: .space 1",
            "\t.text",
            "\tli $v0, 14            # syscall 14: read from file",
            "\tli $a0, 0             # file descriptor 0 = stdin",
            "\tla $a1, Lgetchar_buf  # buffer address",
            "\tli $a2, 1             # read exactly 1 byte",
            "\tsyscall",
            "\tblez $v0, Lgetchar_eof # if bytes read <= 0, it's EOF",
            "\tlbu $v0, Lgetchar_buf  # load the byte unsigned into $v0",
            "\tjr $ra",
            "Lgetchar_eof:",
            "\tli $v0, -1            # force -1 for J-- EOF",
            "\tjr $ra",
            "",
            "Lhalt:",
            "\tli $v0, 10            # syscall 10: halt",
            "\tsyscall",
            "",
            "L_div_zero_error:",
            "\t.data",
            "\tL_div_zero_msg: .asciiz \"error: division by zero\\n\"",
            "\t.text",
            "\tla $a0, L_div_zero_msg",
            "\tj error               # jump to generic error handler",
            "",
            "error:",
            "\tli $v0, 4             # syscall 4: print string address in $a0",
            "\tsyscall",
            "\tli $a0, 1             # set the return code to 1",
            "\tli $v0, 17            # syscall 17: exit2, exit with code",
            "\tsyscall"
            "",
            "L_missing_return_error:",
            "\t.data",
            "\tL_miss_ret_msg: .asciiz \"error: function must return a value\\n\"",
            "\t.text",
            "\tla $a0, L_miss_ret_msg",
            "\tli $v0, 4",
            "\tsyscall",
            "\tli $a0, 1",
            "\tli $v0, 17",
            "\tsyscall"

]
